### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by christianromney** [Krilivye/Jocco#1]
I'd might like to give you a hand with this. What is the license and how does one bootstrap?

**Comment by Krilivye** [comment]
Hi, the license is not defined. I don't want this to be an issue, so
MIT/GNU/Public Domain...  For the bootstraping part, everything is build
under eclipse, Using PMD + FindBugs + Checkstyle + maven directly under git.

2012/5/3 Christian Romney <
reply@reply.github.com

> I'd might like to give you a hand with this. What is the license and how
> does one bootstrap?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Krilivye/Jocco/issues/1

## 

## 

Bousquie Pierre
